--1. get distinct gender type: Select distinct(gender) from customer--

--2. total revenue generated by male vs female for better targeted audience--
-- select customer.gender, sum(customer.purchase_amount) as tot_rev
-- from customer
-- group by customer.gender
-- order by tot_rev desc;

--3. which customer used discount but still spent more than avg purchase amount
-- select customer_id, purchase_amount, discount_applied
-- from customer
-- where discount_applied = 'Yes' and purchase_amount > (
-- 	Select avg(purchase_amount) from customer)
-- order by purchase_amount desc;

--4. top 5 categories with highest avg review rating
-- select item_purchased, round(avg(review_rating::numeric),2) as avg_rate
-- from customer 
-- group by item_purchased
-- order by avg_rate desc
-- limit 5;

--5. compare avg shipping purchase_amount b/w std and express shipping type
-- Select round(avg(purchase_amount::numeric),2) as avg_ship, shipping_type
-- from customer
-- where shipping_type in ('Express','Standard')
-- group by shipping_type
-- order by avg_ship desc;

--6. compare avg purchase amount b/w subs and unsubs customer
-- select round(avg(purchase_amount),2) as avg_amt, subscription_status, sum(purchase_amount), count(customer_id)
-- from customer
-- group by subscription_status
-- order by avg_amt desc;

--7. which 5 prods have highest percent of purchases with discounts
-- select item_purchased, 
-- round(100 * SUM(case when discount_applied ='Yes' then 1 else 0 end)/count(*), 2) as dis
-- from customer
-- group by item_purchased
-- order by dis desc
-- limit 5;

--8. Revenue contribution of each age group
-- Select sum(purchase_amount) as sc, age_grp
-- from customer
-- group by age_grp
-- order by sc desc;

--9. segment customers into New, Returning and Loyal based on prev_purchases and show count of each segment
-- with CTE as (
-- select customer_id, previous_purchases,
-- CASE 
-- WHEN previous_purchases = 1 THEN 'NEW'
-- WHEN previous_purchases BETWEEN 2 and 10 THEN 'RETURNING'
-- ELSE 'LOYAL' 
-- END AS segmented_customer 
-- from customer
-- )

-- select segmented_customer, count(*) as number_of_purchases
-- from CTE 
-- group by segmented_customer
-- order by number_of_purchases desc;

--10. top 3 most purchased item within each category
-- with CTE as (
-- select item_purchased, category, count(customer_id) as tot_orders,
-- row_number() over(partition by category order by count(customer_id) desc) as ranked 
-- from customer
-- group by category, item_purchased)

-- select ranked,item_purchased, category, tot_orders
-- from CTE
-- where ranked <=3 

--11. are customers who are repeat buyers(5+ previous purchases) also subscribers?
-- select subscription_status, count(*) as subs_count
-- from customer
-- where previous_purchases > 5
-- group by subscription_status;

--12. revenue contribution of each age group
-- Select age_grp, sum(purchase_amount) as revenue
-- from customer
-- group by age_grp
-- order by revenue desc;


